### ISSUE TITLE
package.json does not refer to this new repo

### ISSUE THREAD

**Issue by alexjeffburke** [liasica/eslint-module-utils#1]
Hi there,

I was looking to remix one of the rules in `eslint-plugin-import` for an internal task at my workplace - the rule I looked at is importing `eslint-module-utils`, but I had a tough time finding the repository because the git link in the package.json file hasn't been updated to point at this repo so I couldn't easily arrive here from npm.

If this repo is the new authoritative source of these bits, would it be possible to update the metadata to reflect that?

Thanks, Alex J Burke.

**Comment by liasica** [comment]
> Hi there,
> 
> I was looking to remix one of the rules in `eslint-plugin-import` for an internal task at my workplace - the rule I looked at is importing `eslint-module-utils`, but I had a tough time finding the repository because the git link in the package.json file hasn't been updated to point at this repo so I couldn't easily arrive here from npm.
> 
> If this repo is the new authoritative source of these bits, would it be possible to update the metadata to reflect that?
> 
> Thanks, Alex J Burke.

Hi, the  npm branch has not changed version (I'm not sure).

So, I'm configure resolutions in package

```
"resolutions": {
    "**/**/eslint-module-utils": "git+https://github.com/liasica/eslint-module-utils.git"
}
```

Glad to help you :)

**Comment by alexjeffburke** [comment]
Hi there, thanks - I was actually looking for the original source of the files and I realised it isn’t this repository is not where the npm package is published from, it’s actually the utils folder in https://github.com/benmosher/eslint-plugin-import/tree/master/util. As such, I’ll close this issue :)
